# -*- coding: utf-8 -*-
"""OpenCV 12 Motion Detection(1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dso0y9gp17lm-idspzUfbATATgz2SfM3
"""

import cv2
import datetime

file = "VideoInput/Cam Detection.mp4"
cap = cv2.VideoCapture(file)

ret,frame1 = cap.read()
ret,frame2 = cap.read()
# print(frame1.shape)
fourcc = cv2.VideoWriter_fourcc(*'XVID')
Output = cv2.VideoWriter("Output/MOTION DETECTION1.avi", fourcc, 20.0, (640, 352))

while cap.isOpened():
    diff = cv2.absdiff(frame1,frame2)
    gray = cv2.cvtColor(diff, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray,(9,9),0)
    _, thresh = cv2.threshold(blur, 20, 255, cv2.THRESH_BINARY)
    dilated = cv2.dilate(thresh, None, iterations = 3)
    contours, hierarchy = cv2.findContours(dilated, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    datex = str(datetime.datetime.now())
    font = cv2.FONT_HERSHEY_TRIPLEX
    cv2.putText(frame1,datex,(10,20),font,0.5,(255,255,255),1,cv2.LINE_AA)
    
    
    if contours == None :
        
        cv2.putText(frame1, "STATUS : STATIONARY", (480,15), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,255), 2)
    
    else :
        for contour in contours :
            (x, y, w, h) = cv2.boundingRect(contour)
            if cv2.contourArea(contour) < 50 :
#                 cv2.putText(frame1, "STATUS : STATIONARY", (480,15), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,255), 2)
                continue
            cv2.rectangle(frame1, (x,y), (x+w,y+h), (0,255,0), 2)
            cv2.putText(frame1, "STATUS : MOVEMENT", (480,15), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,255), 2)


    cv2.drawContours(frame1, contours, -1, (0,255,0), 1)
    cv2.imshow('FEED', frame1)
    B = cap.get(cv2.CAP_PROP_FRAME_WIDTH)
    L = cap.get(cv2.CAP_PROP_FRAME_WIDTH)
    
    Output.write(frame1)
#     print(L, ", ", B)
    frame1 = frame2
    ret, frame2 = cap.read()
    
    if cv2.waitKey(40) == 27 :
        break

cv2.destroyAllWindows()



